# Generated by Django 4.2.3 on 2023-12-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_payment_braintree_id_profile_address_profile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
