# Generated by Django 4.2.3 on 2023-12-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='CVV',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Card_Number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Expiration_date',
            field=models.DateField(null=True),
        ),
    ]
