# Generated by Django 4.2.3 on 2023-12-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_payment_cvv_payment_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Expiration_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
