# Generated by Django 4.2.3 on 2023-12-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_payment_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Expiration_date',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
