# Generated by Django 4.2.3 on 2023-12-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_payment_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
