# Generated by Django 4.2.3 on 2023-12-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_payment_cvv_remove_payment_card_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
