# Generated by Django 4.2.3 on 2023-12-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_profile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
