# Generated by Django 4.2.3 on 2023-12-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_profile_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='price_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='price',
        ),
    ]
