# Generated by Django 4.2.3 on 2023-12-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_price_db_remove_profile_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_db',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
