# Generated by Django 4.2.3 on 2024-01-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_price_db_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_db',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
