# Generated by Django 4.2.3 on 2024-01-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_price_db_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price_db',
            old_name='price',
            new_name='closeprice',
        ),
        migrations.AddField(
            model_name='price_db',
            name='openprice',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
