# Generated by Django 4.2 on 2024-10-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_rename_price_price_db_closeprice_price_db_openprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='PIN',
        ),
        migrations.AddField(
            model_name='profile',
            name='secret_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
