# Generated by Django 4.2 on 2025-01-16 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('total_price', models.FloatField(null=True)),
                ('shares', models.FloatField(null=True)),
                ('leverage', models.IntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('otp', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('stock_purchase_price', models.FloatField(null=True)),
                ('total_purchase_amount', models.FloatField(null=True)),
                ('bought', models.BooleanField(default=False)),
                ('shares', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Long',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=10)),
                ('amount', models.FloatField(default=0)),
                ('leverage', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('current_price', models.FloatField(null=True)),
                ('long_price', models.FloatField(null=True)),
                ('returns', models.FloatField(null=True)),
                ('open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True)),
                ('amount', models.FloatField(default=1000)),
                ('description', models.TextField(blank=True, max_length=150)),
                ('paid', models.BooleanField(default=False)),
                ('braintree_id', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('total_selling_amount', models.FloatField(null=True)),
                ('stock_selling_price', models.FloatField(null=True)),
                ('sold', models.BooleanField(default=False)),
                ('shares', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=10)),
                ('amount', models.FloatField(default=0)),
                ('leverage', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('current_price', models.FloatField(null=True)),
                ('short_price', models.FloatField(null=True)),
                ('returns', models.FloatField(null=True)),
                ('open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('shares', models.FloatField(null=True)),
                ('equity', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True)),
                ('balance', models.FloatField(default=0)),
                ('stock_eq', models.FloatField(default=0)),
            ],
        ),
    ]
