# Generated by Django 4.2 on 2025-05-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_open_long_is_open_rename_open_short_is_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='shares',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='shares',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock_wallet',
            name='shares',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
