# Generated by Django 4.2 on 2025-09-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_buy_shares_alter_sell_shares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='stock_selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='total_selling_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
