# Generated by Django 4.2.3 on 2023-12-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_braintree_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AlterField(
            model_name='payment',
            name='braintree_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
