# Generated by Django 4.2.3 on 2023-12-08 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0004_remove_payment_user_alter_payment_braintree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.OneToOneField(default=1234, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
