# Generated by Django 4.2.3 on 2024-01-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_buy_sell_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='purchase_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
