# Generated by Django 4.2.3 on 2024-01-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_buy_purchase_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
