# Generated by Django 4.2.3 on 2024-01-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_rename_purchase_amount_buy_stock_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='shares',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
