# Generated by Django 4.2.3 on 2024-01-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_buy_user_payment_user_sell_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_purchase_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
