# Generated by Django 4.2.3 on 2024-01-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_alter_buy_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_eq', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='amount',
            old_name='total_purchase_price',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='total_purchase_price',
            new_name='total_purchase_amount',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='selling_amount',
        ),
        migrations.AddField(
            model_name='sell',
            name='stock_selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='total_selling_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
