# Generated by Django 4.2.3 on 2024-01-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='shares',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sell',
            name='shares',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
