# Generated by Django 4.2.3 on 2024-03-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_amount_shares_alter_payment_amount_alter_sell_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('shares', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('equity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
