# Generated by Django 4.2 on 2024-10-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_stock_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='shares',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='amount',
            name='total_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='shares',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='stock_purchase_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='total_purchase_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='sell',
            name='shares',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='stock_selling_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='total_selling_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock_wallet',
            name='equity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock_wallet',
            name='shares',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='stock_eq',
            field=models.FloatField(default=0),
        ),
    ]
