# Generated by Django 4.2 on 2024-10-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_alter_amount_shares_alter_amount_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
