# Generated by Django 4.2 on 2024-10-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_amount_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
