# Generated by Django 4.2 on 2024-10-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_amount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
